# Generated by Django 4.2.27 on 2025-12-30 15:02

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pep_plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoteiroReuniaoBimestral',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='RoteiroReuniaoID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='RoteiroReuniaoUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('data_reuniao', models.DateField(db_column='DataReuniao')),
                ('horario', models.TimeField(db_column='Horario')),
                ('coordenador_nacional', models.CharField(db_column='CoordenadorNacional', max_length=255)),
                ('participantes', models.TextField(db_column='Participantes', help_text='Lista de todos os participantes presentes na reunião')),
                ('resumo_agenda', models.JSONField(blank=True, db_column='ResumoAgenda', default=list, help_text='Lista de tópicos discutidos durante a reunião')),
                ('desafios_solucoes', models.TextField(db_column='DesafiosSolucoes', help_text='Principais desafios enfrentados e soluções aplicadas')),
                ('oportunidades_praticas', models.TextField(db_column='OportunidadesPraticas', help_text='Oportunidades identificadas e práticas bem-sucedidas')),
                ('analise_dados_tendencias', models.TextField(db_column='AnaliseDadosTendencias', help_text='Análise de dados e tendências identificadas')),
                ('acoes_definidas', models.TextField(db_column='AcoesDefinidas', help_text='Ações definidas, responsáveis e prazos')),
                ('data_proxima_reuniao', models.DateField(blank=True, db_column='DataProximaReuniao', null=True)),
                ('observacoes_proxima_reuniao', models.TextField(blank=True, db_column='ObservacoesProximaReuniao', null=True)),
            ],
            options={
                'db_table': 'tblRoteiroReuniaoBimestral',
                'ordering': ['-data_reuniao'],
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
