# Generated by Django 4.2.27 on 2025-12-30 15:51

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
        ('pep_plus', '0002_roteiroreuniaobimestral'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioSupervisaoBimestral',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='RelatorioSupervisaoID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='RelatorioSupervisaoUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('nome_supervisores', models.TextField(db_column='NomeSupervisores', help_text='Nome(s) do(s) supervisor(es) responsável(eis) pelo relatório')),
                ('num_sessoes_supervisionadas', models.IntegerField(db_column='NumSessoes', default=0, help_text='Quantidade total de sessões acompanhadas no bimestre')),
                ('num_tecnicos_supervisionados', models.IntegerField(db_column='NumTecnicos', default=0, help_text='Total de técnicos formadores supervisionados')),
                ('periodo', models.IntegerField(choices=[(1, 'Janeiro e Fevereiro'), (2, 'Março e Abril'), (3, 'Maio e Junho'), (4, 'Julho e Agosto'), (5, 'Setembro e Outubro'), (6, 'Novembro e Dezembro')], db_column='Periodo')),
                ('ano', models.IntegerField(db_column='Ano')),
                ('periodo_inicio', models.DateField(db_column='PeriodoInicio')),
                ('periodo_fim', models.DateField(db_column='PeriodoFim')),
                ('avaliacoes_tecnicos', models.JSONField(blank=True, db_column='AvaliacoesTecnicos', default=list, help_text='Avaliações dos técnicos formadores supervisionados')),
                ('notas_sessoes_pep', models.JSONField(blank=True, db_column='NotasSessoes', default=dict, help_text='Notas dos 10 passos das sessões supervisionadas')),
                ('observacoes_adicionais', models.TextField(blank=True, db_column='ObservacoesAdicionais', help_text='Observações complementares para discussão', null=True)),
                ('distrito', models.ForeignKey(db_column='DistritoID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relatorios_supervisao', to='location.location')),
                ('modulo_maior_dificuldade', models.ForeignKey(blank=True, db_column='ModuloDificuldadeID', help_text='Módulo com menor nota (maior dificuldade)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relatorios_dificuldade', to='pep_plus.moduloeducacional')),
            ],
            options={
                'db_table': 'tblRelatorioSupervisaoBimestral',
                'ordering': ['-ano', '-periodo'],
                'managed': True,
                'unique_together': {('distrito', 'periodo', 'ano')},
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
